In [18]:
# importing the dataset

import pandas as pd
import numpy as np
import gym
import random
import time
from IPython.display import clear_output

In [19]:
# creating the environment

env = gym.make("Taxi-v3")
env.render()

+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+



In [20]:
action_size = env.action_space.n
print("Action_size:",action_size)
state_size = env.observation_space.n
print("State_size :",state_size)

Action_size: 6
State_size : 500


In [21]:
# creating the q table 

q_table = np.zeros((state_size, action_size))
print(q_table)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 ...
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [22]:
# number of episodes
num_episodes = 10000
# no of steps in an episode
max_steps = 1000
# learning rate
lr = 0.2
exploration_decay_rate = 0.001
gamma = 0.8
exploration_rate = 1
max_exploration_rate = 1
min_exploration_rate = 0.01

In [24]:
# training

rewards_all_episodes = []

for episode in range(num_episodes):
    state = env.reset()
    done = False
    
    rewards_current_episode = 0
    
    for step in range(max_steps):
        # selecting a random value , 0 or 1
        random_value = random.uniform(0,1)
        
        if random_value > exploration_rate:
            action = np.argmax(q_table[state,:])
        else:
            action = env.action_space.sample()
            
        new_state, reward, done, info = env.step(action)
        
        # updating the q table
        q_table[state,action] = q_table[state,action] + lr * (reward + gamma*np.max(q_table[new_state,:]) - q_table[state,action])
        
        state = new_state
        rewards_current_episode += reward
        
        if done==True:
            break
    
    exploration_rate = min_exploration_rate + (max_exploration_rate - min_exploration_rate) * np.exp(-exploration_decay_rate * episode)
    
    rewards_all_episodes.append(rewards_current_episode)
        

In [28]:
rewards_all_episodes[9999]

9

In [29]:
# testing 

for episode in range(3):
    state = env.reset()
    done = False
    
    print("Episode :",episode+1)
    time.sleep(1)
    
    for step in range(max_steps):
        
        clear_output(wait=True)
        
        env.render()
        time.sleep(0.3)
        
        action = np.argmax(q_table[state,:])
        
        new_state,reward,done,info = env.step(action)
        
        if done:
            clear_output(wait=True)
            env.render()
                
            clear_output(wait = True)
            
            break
        state=new_state
env.close()

+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (Dropoff)
